name: example
description: A flutterwave example project.

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutterwave_standard:
    path: "../"
  cupertino_icons: ^1.0.6
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
flutter:

  uses-material-design: true
