name: Publish changes to Pub.dev

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read
  
jobs:
  check-readme-and-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: check for changes in readme and changelog files
        run: |
          if ! git diff --quiet HEAD~ HEAD -- README.md CHANGELOG.md; then
            echo "README and/or CHANGELOG have been modified. Proceeding with deployment."
          else
            echo "README and/or CHANGELOG have not been modified. Terminating deployment."
            exit 1
          fi

      - name: push build status to slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always()

  publish:
    needs: check-readme-and-changelog
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"

      - name: install flutter dependencies
        run: flutter pub get

      - name: Publish to Pub.dev
        run: flutter pub publish --dry-run

      - name: push build status to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always()
